baseURL = 'https://hgeorgiev.com/blog'
languageCode = 'en-us'
title = 'hgeorgiev.com'

theme = ["github.com/setsevireon/photophobia"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""

[languages.en]
title = "hgeorgiev.com/blog"
weight = 1
contentDir = "content"

[sitemap]
changefreq = "daily"
priority = 0.5
filename = "sitemap.xml"

[markup.highlight]
style = "native"
